version: "3.8"

services:
  database:
    image: mongo:4.0.4
    container_name: database
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=newmodels
    volumes:
      - dbdata:/usr/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    command: npm run start
    container_name: GMM
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=database
    depends_on:
      - database
    links:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

volumes:
  dbdata:
