version: "3.8"

services:
  database:
    image: mongo:4.0.4
    container_name: GMM_Database
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=newmodels
    volumes:
      - dbdata:/usr/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  reports:
    container_name: GMM_Reports
    build:
      context: ../declaraciones-patrimoniales-reportes
      args:
        - NODE_ENV=${NODE_ENV:-development}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: GMM-Elasticsearch
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    command: npm run start
    container_name: GMM
    restart: unless-stopped
    depends_on:
      - database
      - elasticsearch
      - reports
    links:
      - database
      - elasticsearch
      - reports
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

volumes:
  dbdata:
  esdata:
    driver: local
