version: "3"

services:
  reports:
    build:
      context: ../SistemaDeclaraciones_reportes
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - 3001:3001

  elasticsearch:
    image: elasticsearch:7.11.1
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    network_mode: host
    depends_on:
      - elasticsearch
      - reports
    volumes:
      - .:/usr/app

volumes:
  esdata:
