version: "3"

volumes:
  dbdata:

services:
  database:
    image: mongo:4-bionic
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - dbdata:/usr/data/db
    ports:
      - 27017:27017

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    links:
      - database
    ports:
      - ${PORT}:${PORT}
