version: "3"

services:
  database:
    image: mongo:4-bionic
    container_name: GMM_Database
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - dbdata:/usr/data/db

  reports:
    container_name: GMM_Reports
    build:
      context: ../SistemaDeclaraciones_reportes
      args:
        - NODE_ENV=${NODE_ENV}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: GMM-Elasticsearch
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: GMM
    restart: unless-stopped
    depends_on:
      - database
      - elasticsearch
      - reports
    links:
      - database
      - elasticsearch
      - reports
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app

volumes:
  dbdata:
  esdata:
